name: Ruff
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Ruff Lint Checker
        uses: astral-sh/ruff-action@v3
      - name: Run Ruff Format Checker
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check